# Настройки бота
bot:
  prefix: "!"
  status: "Economy Bot"

# Настройки API сервера
api:
  host: "0.0.0.0"
  port: 5001
  # API ключ загружается из переменной окружения API_KEY
  # Не указывайте ключ здесь в целях безопасности!

# Настройки экономики
economy:
  starting_balance: 1000
  currency_name: "монет"
  currency_symbol: "💰"

# Настройки базы данных
database:
  type: "json"  # Можно изменить на "sqlite" или "postgresql"
  path: "data/economy.json"

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/bot.log"