name: EconomyBridge
version: '${project.version}'
main: com.discordbot.economybridge.EconomyBridge
api-version: '1.20'
depend: [PlaceholderAPI]
softdepend: [Geyser-Spigot, floodgate]
commands:
  balance:
    description: Показать ваш баланс
    usage: /balance
    aliases: [bal, money]
  pay:
    description: Перевести деньги другому игроку
    usage: /pay <игрок> <сумма>

permissions:
  economybridge.admin:
    description: Доступ к административным командам плагина
    default: op
  economybridge.use:
    description: Доступ к основным командам плагина
    default: true