# Конфигурация EconomyBridge

# Настройки API
api:
  # URL API сервера нашего бота
  url: 'http://localhost:5001'
  # API ключ будет загружен из переменной окружения API_KEY
  # Этот ключ используется для подписи запросов между плагином и ботом
  # Он должен быть одинаковым на стороне бота и плагина
  # Не указывайте ключ здесь! Используйте переменную окружения для безопасности
  key: '' # Будет установлен через переменную окружения

# Настройки PlaceholderAPI
placeholders:
  # Формат отображения баланса
  balance: '%economy_balance%'

# Интервал обновления данных (в секундах)
update_interval: 30

# Настройки для Bedrock игроков
bedrock:
  # Включить поддержку Bedrock игроков
  enabled: true
  # Префикс для Bedrock игроков (если нужно)
  prefix: '&7[BE] &r'

# Формат сообщений
messages:
  balance: '&aВаш баланс: &f%economy_balance% монет'
  pay_success: '&aВы перевели &f%amount% монет&a игроку &f%player%'
  pay_error: '&cОшибка при переводе: %error%'