name: EconomyBridge
version: '${project.version}'
main: com.discordbot.economybridge.EconomyBridge
api-version: '1.20'
depend: [PlaceholderAPI, floodgate, Vault]
softdepend: [Geyser-Spigot, DiscordSRV, LuckPerms, CoreProtect, WorldGuard, ClansLite]
commands:
  balance:
    description: Показать ваш баланс
    usage: /balance
    aliases: [bal, money]
  pay:
    description: Перевести деньги другому игроку
    usage: /pay <игрок> <сумма>
  reward:
    description: Получить награду за игровое время
    usage: /reward
  checkapi:
    description: Проверить работу API (только для администраторов)
    usage: /checkapi
    permission: economybridge.admin
    permission-message: §cУ вас нет прав для использования этой команды!

permissions:
  economybridge.admin:
    description: Доступ к административным командам плагина
    default: op
  economybridge.use:
    description: Доступ к основным командам плагина
    default: true